// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1315d46f8066eec8c197914da88e98629ebc2254/moment/moment.d.ts
declare var moment: moment.MomentStatic;
